export function generateAppLang(projectName: string): string {
  return `project "${projectName}"

description "Generated by ALang"

stack {
    frontend react
    backend fastapi
    database postgresql
}

team {
    architect
    backend
    frontend
    qa
}
`;
}
