export function generateReadme(projectName: string): string {
  return `# ${projectName}

Generated by ALang — Programming by Intent. Built by AI.

## Getting Started

Edit \`app.alang\` to define your project intent, then use the ALang CLI to plan and build.

\`\`\`bash
alang plan
alang build
\`\`\`
`;
}
