import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { AlangError, parse } from "../src/index.js";

const VALID_SOURCE = `
project Ecommerce

description "Example"

frontend React
backend FastAPI
database PostgreSQL

deployment Railway

auth Clerk

agents
  architect
  backend
  frontend
  qa
`;

describe("parse", () => {
  it("parses a valid ALang document", () => {
    const ast = parse(VALID_SOURCE);

    assert.equal(ast.project, "Ecommerce");
    assert.equal(ast.description, "Example");
    assert.deepEqual(ast.stack, {
      frontend: "React",
      backend: "FastAPI",
      database: "PostgreSQL",
    });
    assert.equal(ast.deployment, "Railway");
    assert.equal(ast.auth, "Clerk");
    assert.deepEqual(ast.agents, [
      "architect",
      "backend",
      "frontend",
      "qa",
    ]);
  });

  it("parses quoted project names and escaped strings", () => {
    const ast = parse(`
project "my-alang-app"

description "Generated by ALang"

frontend react
backend fastapi
database postgresql

agents
  qa
`);

    assert.equal(ast.project, "my-alang-app");
    assert.equal(ast.description, "Generated by ALang");
    assert.equal(ast.stack.frontend, "react");
    assert.deepEqual(ast.agents, ["qa"]);
  });

  it("allows comments and blank lines", () => {
    const ast = parse(`
# ecommerce intent
project Shop

frontend React

# team
agents
  architect
`);

    assert.equal(ast.project, "Shop");
    assert.equal(ast.stack.frontend, "React");
    assert.deepEqual(ast.agents, ["architect"]);
  });

  it("rejects files without a project declaration", () => {
    assert.throws(
      () =>
        parse(`
description "Missing project"
frontend React
agents
  qa
`),
      (error: unknown) => {
        assert.ok(error instanceof AlangError);
        assert.match(error.message, /Expected a project declaration/);
        return true;
      },
    );
  });

  it("rejects duplicate stack declarations", () => {
    assert.throws(
      () =>
        parse(`
project Demo
frontend React
frontend Vue
agents
  qa
`),
      (error: unknown) => {
        assert.ok(error instanceof AlangError);
        assert.match(error.message, /Duplicate 'frontend' declaration/);
        return true;
      },
    );
  });

  it("rejects description values that are not quoted strings", () => {
    assert.throws(
      () =>
        parse(`
project Demo
description Example
agents
  qa
`),
      (error: unknown) => {
        assert.ok(error instanceof AlangError);
        assert.match(
          error.message,
          /Expected a quoted string after 'description'/,
        );
        return true;
      },
    );
  });

  it("rejects empty agents blocks", () => {
    assert.throws(
      () =>
        parse(`
project Demo
frontend React
agents
  # no agents listed
`),
      (error: unknown) => {
        assert.ok(error instanceof AlangError);
        assert.match(
          error.message,
          /agents' block must include at least one agent/,
        );
        return true;
      },
    );
  });

  it("rejects duplicate agents", () => {
    assert.throws(
      () =>
        parse(`
project Demo
frontend React
agents
  qa
  qa
`),
      (error: unknown) => {
        assert.ok(error instanceof AlangError);
        assert.match(error.message, /Duplicate agent 'qa'/);
        return true;
      },
    );
  });

  it("rejects unknown top-level keywords", () => {
    assert.throws(
      () =>
        parse(`
project Demo
frontend React
monitoring Datadog
agents
  qa
`),
      (error: unknown) => {
        assert.ok(error instanceof AlangError);
        assert.match(error.message, /Unknown keyword 'monitoring'/);
        return true;
      },
    );
  });

  it("rejects unterminated string literals", () => {
    assert.throws(
      () =>
        parse(`
project Demo
description "oops
frontend React
agents
  qa
`),
      (error: unknown) => {
        assert.ok(error instanceof AlangError);
        assert.match(error.message, /Unterminated string literal/);
        return true;
      },
    );
  });

  it("rejects documents with no stack fields or agents", () => {
    assert.throws(
      () =>
        parse(`
project Demo
description "Too minimal"
`),
      (error: unknown) => {
        assert.ok(error instanceof AlangError);
        assert.match(error.message, /Add at least one stack field/);
        return true;
      },
    );
  });
});
